### ISSUE TITLE
Add new front matter variable: `short_title`

### ISSUE THREAD

**Issue by tachyondecay** [symphonycms/docs.getsymphony.com#21]
@bernardodiasc I am loving the navigation templates being used in the sidebar and for the `list` layout!

However, the sidebar is very narrow, and anything with a long title results in the link wrapping. We can make some styling tweaks later to help this, of course. But it’s motivating me to give my docs shorter titles—which isn’t always a bad thing.

Sometimes, though, you just need a lengthy title—I’m thinking of articles and tutorials—but it’s OK to abbreviate the title for things like navigation links.

I propose we add a new (optional) variable to the front matter, `short_title`, and have the sidebar nav template use this as its first choice for a link label. If `short_title` is missing/empty, it will fall back to `title`.

**Comment by bernardodiasc** [comment]
This is a good topic. I've been checking a lot documentation sites to see how they are doing. Usually is only one list, everything under categories. Works for small libs, not compatible with our docs. But this is related because the sidebar is small, and titles are too. Which is good, because the subject is much easier to identify.

That said, go for it. +1 for `short_title`
